<?php
 return [
   [
    "name" => "Stephen King",
    "life_story" => "Stephen King è autore di romanzi e racconti best seller che attingono ai filoni dell’orrore, del fantastico e della fantascienza, ed è considerato un maestro nel trasformare le normali situazioni conflittuali della vita – rivalità fra coetanei, tensioni e infedeltà coniugali – in momenti di terrore. Quando è ancora piccolo, sua madre deve far fronte a grandi difficoltà, perché il padre uscito di casa per fare una passeggiata non fa più ritorno. Nel 1962 inizia a frequentare la Lisbon High School e comincia a spedire i suoi racconti a vari editori di riviste, senza però alcun successo concreto. Conclusi gli studi superiori entra all'Università del Maine ad Orono, dove gestisce per un paio d'anni una rubrica all'interno del giornale universitario. Nel 1967 termina un primo racconto breve a cui fa seguito, qualche mese dopo, il romanzo La lunga marcia che riceve giudizi lusinghieri. Sottopone Carrie alla casa editrice Doubleday e ottiene un assegno di 2500 dollari come anticipo per la pubblicazione del romanzo. A maggio arriva la notizia che la Doubleday ha venduto i diritti dell'opera alla New American Library per 400.000 dollari, metà dei quali spettano di diritto all'autore. Così, a ventisei anni, Stephen King lascia l'insegnamento per dedicarsi alla professione di scrittore. Da quel momento la sua carriera non avrà più interruzioni. Nel 1971 si sposerà con Tabitha, conosciuta due anni prima lavorando nella biblioteca dell'Università. Con un'operazione innovativa, il 14 marzo 2000 diffonderà esclusivamente su Internet il racconto Riding the Bullet. Nell'autunno dello stesso anno pubblicherà On writing: autobiografia di un mestiere, un'autobiografia e una serie di riflessioni su come nasca la scrittura. Tra i suoi libri più noti si ricordano Shining (1976; il film, del 1980, venne diretto da Stanley Kubrick); La zona morta (1979; versione cinematografica del 1983, per la regia di David Cronenberg); Christine la macchina infernale (1983; il film, dello stesso anno, è di John Carpenter); It (1986, il film è del 1990); Misery (1987; noto in Italia con il titolo Misery non deve morire, la pellicola è stata realizzata da Rob Reiner nel 1990), Mr Mercedes (2014). Tra gli altri ricordiamo: Cuori in Atlantide (2000), La casa del buio (2002), Notte buia, niente stelle (2010), Chi perde paga (2015), Fine turno (2016), The Outsider (2018), Elevation (2019), L'istituto (2019) e Later (2021). È del 2016 la nuova edizione aggiornata di Danse macabre, pubblicato da Frassinelli con l'introduzione e cura di Giovanni Arduino. A Stephen King è stata assegnata nel 2003 la National Book Foundation Medal per il contributo alal letteratura americana, e nel 2007 l'Associazione Mystery Writers of America gli ha conferito il Grand Master Award.",
    "author_year" => "1947",
    "where" => "Portland, Maine"
   ],
   [
    "name" => "Jane Austen",
    "life_story" => "Scrittrice inglese. Compì la sua educazione quasi interamente in casa, sotto la guida del padre ecclesiastico. Nel 1801 si trasferì con la famiglia a Bath; nel 1805, dopo la morte del padre, a Southampton; poi, nel 1809, a Chawton, Hampshire, dove scrisse quasi tutti i suoi romanzi.",
    "author_year" => "1775",
    "where" => "Steventon, Hampshire"
   ],
   [
    "name" => "John R. R. Tolkien",
    "life_story" => "Scrittore inglese. Autore di notevoli opere filologiche sulle leggende medievali sassoni e celtiche, docente di lingua e letteratura inglesi a Oxford (1925-1959), ha scritto alcuni famosi romanzi ispirati a motivi della letteratura fantastica medievale: 'Lo Hobbit' (1937) e la trilogia de 'Il signore degli anelli' (1954-55). Il successo di questi romanzi, che nel loro insieme costituiscono un'unica saga, è stato tale da costituire un fenomeno socioculturale molto importante.
    Tolkien è riuscito, nonostante la complessità degli intrecci, a creare una mirabile fusione tra motivi apparentemente disparati che, in realtà, interpretano sia le inquietudini, sia i sogni del nostro tempo.
    Se da un lato lo scrittore costruisce con deliziosa e ricca inventiva un racconto di pura evasione, dall'altro evidenzia nel comportamento dei protagonisti non i lati erotici e cavallereschi, ma virtù quotidiane, quali il buonsenso, la perseveranza, la pazienza.",
    "author_year" => "1892",
    "where" => "Bloemfontein"
   ],
   [
    "name" => "Sarah Pekkanen",
    "life_story" => "Sarah Pekkanen, nata a New York, si è subito trasferita con i genitori in una tranquilla cittadina del Maryland, dove vive tuttora con il marito e i tre figli. Dopo la laurea, ha lavorato per qualche anno come giornalista. Ha deciso, in seguito, di prendersi una pausa per dedicarsi alla sua vera passione, la scrittura. L'amore non è il mio forte (Piemme 2012), il suo primo romanzo, ha ottenuto un grande successo sia in Italia che all'estero. Tra gli altri suoi romanzi ricordiamo Single? No grazie (Piemme 2012) e il thriller La moglie tra di noi (Piemme 2018), scritto in collaborazione con la sua editor Greer Hendricks.",
    "author_year" => "1960",
    "where" => "-",
   ],
   [
    "name" => "Alberto Moravia",
    "life_story" => "Alberto Moravia esordì giovanissimo pubblicando, a sue spese, il primo romanzo, Gli indifferenti (1929). Penetrante e spietato ritratto della borghesia italiana agli inizi del fascismo, l’opera rivelò immediatamente, nella incisività di una prosa secca e analitica, la maturità di uno scrittore capace fin da allora di far tesoro delle diverse lezioni dei grandi modelli europei, dalla oggettività di De Foe alla problematicità dei romanzieri russi (specie Dostoevskij), al realismo tipologico dei francesi dell’Ottocento. Il romanzo, accolto con ostilità dalla cultura fascista che ne proibì la diffusione, fu salutato con entusiasmo solo da pochi critici accorti (Borgese, Pancrazi, Solmi).
    M. cominciò poi a collaborare a riviste e quotidiani, e scrisse un secondo ampio romanzo, Le ambizioni sbagliate (1935), la cui resa analitica, delle psicologie e delle ideologie, è meno felice, se non velleitaria. Colpito dalle leggi razziali, M. fu costretto a firmare i propri articoli con uno pseudonimo, ma continuò a pubblicare racconti (L’imbroglio, 1937; I sogni del pigro, 1940); la satira grottesca di un dittatore sudamericano, La mascherata (1941), fu censurata alla seconda edizione.
    Del 1944 è il romanzo breve Agostino, prova esemplare di analisi dei turbamenti di un adolescente alla rivelazione della sessualità. Segue il pamphlet La speranza, ossia cristianesimo e comunismo (1945), che testimonia di un primo approccio alle tematiche marxiste. La successiva produzione narrativa è intensissima: escono La romana (1947), La disubbidienza (1948), L’amore coniugale e altri racconti (1949), Il conformista (1951), Il disprezzo (1954), Racconti romani (1954), La ciociara (1957), Nuovi racconti romani (1959). Al 1958 risalgono i primi testi teatrali, con la riduzione della Mascherata e con Beatrice Cenci. Nel 1953 M. fonda «Nuovi Argomenti», con A. Carocci, e inizia la propria collaborazione al «Corriere della sera» con racconti e reportages. Questi ultimi saranno via via raccolti in diversi volumi (Un mese in URSS, 1958; Una idea dell’India, 1962; La rivoluzione culturale in Cina, 1968; A quale tribù appartieni?, 1972; Lettere dal Sahara, 1981). Dal 1955 svolge anche attività di critico cinematografico per il settimanale «L’Espresso» (una raccolta di cronache è apparsa col titolo Al cinema, 1975). Nel 1960 La noia (premio Viareggio) ripete il successo dei primi romanzi; seguono opere di impegno diseguale, in cui però il registro narrativo di M. si arricchisce di forme nuove, ora riecheggiando modalità del romanzo sperimentale (soprattutto dell’école du regard), ora approfondendo temi psicoanalitici, con particolare richiamo alle problematiche reichiane sulla sessualità: L’attenzione (1965), Il paradiso (1970), Io e lui (1971), Boh (1976), La vita interiore (1978), 1934 (1982), La cosa (1983), L’uomo che guarda (1985), Viaggio a Roma (1988), Palocco (1990). A questa produzione narrativa si accompagnano ancora lavori drammatici (Il dio Kurt, 1968; La vita è gioco, 1969) e saggi (da ricordare il volume L’uomo come fine e altri saggi, 1963; e le riflessioni sul proprio engagement in Impegno controvoglia, 1981). È stato anche deputato al parlamento europeo (dalla cui esperienza è nato il Diario europeo, postumo, 1993). Postumi sono usciti anche l’Autobiografia (1990, con A. Elkann) e La donna leopardo (1991).
    Il personaggio dello scrittore e dell’intellettuale militante, disponibile a intervenire in campi diversi, in nome di una passione civile e di una curiosità culturale rimaste intatte attraverso decenni, rende M. esemplare di un «impegno» teso costantemente alla razionalità. I diversi modelli letterari che ha frequentato nella sua lunga carriera di narratore, tendenzialmente concentrati attorno al registro del realismo, gli hanno suggerito ampie indagini sulle metodologie e patologie delle classi sociali (privilegiata, in questo, l’alta e media borghesia). Nelle opere più tarde la sua prosa scarna (talora fino all’aridità) appare orientata ad amplificare le strutture dialogiche, quasi ad accentuare e variare – nel senso di una confessione psicoanalitica – il monologo interiore, tipico della grande narrativa novecentesca. Il sesso diviene il filtro per vagliare i rapporti tra individuo e società, tra es e super-io, e indica anche la fedeltà a una tematica marxista e freudiana che M. mostrò di aggiornare con le più recenti ideologie della trasgressione, nel «politico» e nel «privato» (psicoanalisi selvaggia, femminismo ecc.).",
    "author_year" => "1907",
    "where" => "Roma"
   ],
   [
    "name" => "J. K. Rowling",
    "life_story" => "J. K. (Joanne Kathleen) Rowling scrive storie da quando era bambina, e ha sempre desiderato diventare scrittrice. L’ispirazione per Harry Potter le venne anni fa su un treno da Manchester a Londra: arrivata alla stazione di King’s Cross, quasi tutti i personaggi avevano già acquistato carattere.
    Durante gli anni successivi cominciò a delineare la trama di ogni libro e a scrivere il primo della serie, Harry Potter e la Pietra Filosofale, pubblicato da Bloomsbury nel 1997 e da Salani nel 1998. J. K. Rowling ha scritto anche Il Quidditch attraverso i secoli e Gli animali fantastici: dove trovarli, due libri della biblioteca di Harry Potter, in favore dell’associazione inglese senza fini di lucro Comic Relief. Le avventure di Harry Potter hanno segnato una svolta nella letteratura per ragazzi, sono da anni in testa a tutte le classifiche dei bestseller internazionali e hanno ricevuto infiniti premi letterari.
    La serie è entrata nel Guinness dei primati come più grande fenomeno editoriale di tutti i tempi.
    Grande successo ha avuto anche il suo primo romanzo per adulti: Il seggio vacante, edito da Salani nel 2012.
    Sempre per le edizioni Salani dal 2013 in libreria anche la nuova serie (per adulti e firmata con lo pseudonimo Robert Galbraith) con protagonista l'investigatore privato Cormoran Strike. Il primo titolo è Il richiamo del cuculo.
    Nel 2016 è uscito Harry Potter e la maledizione dell'erede, uno spettacolo teatrale di Jack Thorne su soggetto di J. K. Rowling, con il contributo di John Tiffany. Il copione dell'opera, ambientata diciannove anni dopo il settimo libro, è stato pubblicato da editori di tutto il mondo, riscuotendo un enorme successo di pubblico. Nel 2017 Salani pubblica Buona vita a tutti, che riporta il discorso che l'autrice ha tenuto per la cerimonia di laurea ad Harvard. Nel 2020 esce per Salani L' Ickabog una favola scritta dall’autrice oltre dieci anni fa per i suoi figli,illustrata con i disegni di 34 piccoli fan italiani, mentre nel 2021 viene pubblicata la favola natalizia Il Maialino di Natale (Salani).",
    "author_year" => "1965",
    "where" => "Bristol"
   ],
];